# -*- coding: utf-8 -*-
"""Sentence Similarity Project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TVET0YJgI3ztyYTBYV8u8E0X6u5WP4tV
"""

!pip install sentence-transformers

from sentence_transformers import SentenceTransformer,util
model = SentenceTransformer('all-MiniLM-L6-V2')
text1 = input("Enter Text 1: ")
text2 = input("Enter Text 2: ")
embedding1 = model.encode(text1)
embedding2 = model.encode(text2)
similarity = util.cos_sim(embedding1, embedding2)
print("\nsimilarity score:",round(float(similarity),2))

if similarity>0.75:
  print("similarity Level:High")
elif similarity>0.4:
  print("similarity Level:Medium")
else:
   print("similarity Level:Low")

